### ISSUE TITLE
Image not displaying(Warzone Window)

### ISSUE THREAD

**Issue by rocknot1p7** [rvl1382002/stonePaperScissors#6]
Branch:-**rvl1382001-functions-image-error**

image stone.png, paper.png, scissor.png are not displaying correctly in warzone(single player& multiplayer) window buttons(bL1,bL2,bL3,bR1,bR2,bR3)
fix needed!
buttons should display this images

**Comment by rvl1382002** [comment]
fix done. now the buttons are showing the images. When a PhotoImage object is garbage-collected by Python (e.g. when you return from a function that stored an image in a local variable), the image is cleared even if it’s being displayed by a Tkinter widget. So all we needed was to declare those stoneImg, paperImg, and scissorImg variables as global
